( This gcode generated by /home/mattvenn/.eagle/ulp/pcb-gcode.ulp )
( Copyright 2005 by John Johnson. See readme.txt for licensing terms. )

( This file generated from the board /home/mattvenn/eagle-circuit-designs/cvm/hymera.brd )
( This file generated 30/01/2012 16:46 )

G21

G90
G00 Z10.0000 
G00 X0 Y0
M03
G04 P3.000000
(File Footer)
G00 Z10.0000 
M05
M02
